title: Outragefatigue.blog
default_lang: 'United States'
author:
  name: Jerry
  email: g.gravitas@gmail.com
taxonomies:
  - category
  - tag
  - month
  - author
metadata:
  description: 'Sick and tired or being sick and tired'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: ''
